
  defaultMarkdownHandler: goldmark
  highlight:
    style: borland
    codeFences: true
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 2
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2 